### ISSUE TITLE
New player categorization

### ISSUE THREAD

**Issue by nytpu** [MusicPlayerDaemon/website#121]
I just wrote a simple little client that I would like to add to the [client list](https://github.com/MusicPlayerDaemon/website/blob/master/content/clients/index.md): <https://git.sr.ht/~nytpu/bgm-mpd>.  However, I'm unsure exactly where it should be categorized because it's an odd client: it automatically plays a single track, pauses for a random period of time, and then plays the next track (emulating how some video games play background music).  I was thinking under “Utility Clients” or maybe “Non-Interactive Clients”, but it'd also fit under plain “Command-Line Clients”.  Or maybe it's just not a good fit at all for that list, that's fine too.  I can make a pull request if it's determined that the client is suitable to be added and what category it belongs to.

**Comment by jcorporation** [comment]
I would add it to "Utility Clients".

**Comment by nytpu** [comment]
Yeah, that's what I was thinking.  Thanks
