### ISSUE TITLE
Roon reference in commercial.html page

### ISSUE THREAD

**Issue by vonodna** [MusicPlayerDaemon/website#6]
Hi Max,

I just opened this issue in order to discuss about Roon implementation in Linux streamers. I read your page referring to Roon MPD patch and  I would like to discuss about it.

As far as I am concerned, the most popular Roon implementation (in audio distributions that use MPD), is Roonbridge:

http://kb.roonlabs.com/LinuxInstall

Roonbridge is in fact a propietary Roon client receiving data from another machine which acts like a Roon server. All this procedure has nothing to do with MPD.

If course there's a possibility that some of these companies have written proprietary code for a Roon MPD plugin, but I am 99% sure that they just use Roonbridge in parallel with MPD.

**Comment by MaxKellermann** [comment]
I know all of this, but I have evidence that Cary Audio has linked proprietary code from Roon's RAAT SDK statically into the MPD binary.

**Comment by vonodna** [comment]
Thanks for your reply. I assume there's no need for this issue to be open.
