### ISSUE TITLE
Add EasyMPD

### ISSUE THREAD

**Issue by parkmino** [MusicPlayerDaemon/website#7]
I think you should know about EasyMPD.
It provides web interface on top of MPD for Alix, APU and Raspberry Pi.
It is commercial software and selling price is around $60.
I cannot find any information about GPL at Korean homepage.

http://easympd.com/index.php

**Comment by MaxKellermann** [comment]
Thanks.

A GPL offer is only required to be given to those who also got the software, so this is ok so far. So it would be interesting to have the firmware image, and to request the source code.

**Comment by MaxKellermann** [comment]
809d7b4d02c1bfbd2121720b7b150bd5f28690bd
