### ISSUE TITLE
Poly by chord electronics might be using MPD

### ISSUE THREAD

**Issue by estshorter** [MusicPlayerDaemon/website#8]
According to this [user manual](https://chordelectronics.co.uk/wp-content/uploads/2017/01/Poly-User-Manual-English.pdf) and other announce, poly can be controlled by MPD clients.
However, I'm not sure whether it includes MPD software.
I think you should ask chord about it.

**Comment by MaxKellermann** [comment]
e3246567bb69f898b1e3a4a62ce6967197034a57

**Comment by estshorter** [comment]
I'm sorry but I don't understand what you say.

**Comment by MaxKellermann** [comment]
That's the commit id which added the vendor: https://github.com/MusicPlayerDaemon/website/commit/e3246567bb69f898b1e3a4a62ce6967197034a57

**Comment by estshorter** [comment]
I got it. Thanks.
